### ISSUE TITLE
Doesn't work for API level 19

### ISSUE THREAD

**Issue by madongfly** [madongfly/grpc-android-test#1]
[INFO]: Running gRpc Android test

```
io.grpc.android.integrationtest.TesterActivityTest:
Failure in testGrpc:
junit.framework.ComparisonFailure: expected:<[Succeed!!!]> but was:<[Failed... : io.grpc.StatusRuntimeException: INTERNAL: Failed starting transport
com.google.common.util.concurrent.UncheckedExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Failed starting transport
    at io.grpc.stub.Calls.getUnchecked(Calls.java:117)
    at io.grpc.stub.Calls.blockingUnaryCall(Calls.java:129)
    at io.grpc.android.integrationtest.TestServiceGrpc$TestServiceBlockingStub.emptyCall(TestServiceGrpc.java:331)
    at io.grpc.android.integrationtest.IntegrationTester.emptyUnary(IntegrationTester.java:77)
    at io.grpc.android.integrationtest.IntegrationTester.runTest(IntegrationTester.java:56)
    at io.grpc.android.integrationtest.GrpcTestTask.doInBackground(GrpcTestTask.java:49)
    at io.grpc.android.integrationtest.GrpcTestTask.doInBackground(GrpcTestTask.java:12)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Failed starting transport
    at io.grpc.Status.asRuntimeException(Status.java:428)
    at io.grpc.stub.Calls$UnaryStreamToFuture.onClose(Calls.java:324)
    at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$3.run(ChannelImpl.java:402)
    at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
    ... 3 more
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb7971fb0: Failure in SSL library, usually a protocol error
error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available (external/openssl/ssl/s23_clnt.c:486 0xabd7dd5c:0x00000000)
    at io.grpc.transport.okhttp.OkHttpClientTransport.start(OkHttpClientTransport.java:300)
    at io.grpc.ChannelImpl.obtainActiveTransport(ChannelImpl.java:199)
    at io.grpc.ChannelImpl.access$600(ChannelImpl.java:55)
    at io.grpc.ChannelImpl$CallImpl.start(ChannelImpl.java:266)
    at io.grpc.stub.Calls.asyncServerStreamingCall(Calls.java:174)
    at io.grpc.stub.Calls.unaryFutureCall(Calls.java:86)
    at io.grpc.stub.Calls.blockingUnaryCall(Calls.java:129)
    at io.grpc.android.integrationtest.TestServiceGrpc$TestServiceBlockingStub.emptyCall(TestServiceGrpc.java:331)
    at io.grpc.android.integrationtest.IntegrationTester.emptyUnary(IntegrationTester.java:77)
    at io.grpc.android.integrationtest.IntegrationTester.runTest(IntegrationTester.java:56)
    at io.grpc.android.integrationtest.GrpcTestTask.doInBackground(GrpcTestTask.java:49)
    at io.grpc.android.integrationtest.GrpcTestTask.doInBackground(GrpcTestTask.java:12)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    ... 3 more
Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb7971fb0: Failure in SSL library, usually a protocol error
error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available (external/openssl/ssl/s23_clnt.c:486 0xabd7dd5c:0x00000000)
    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
    at com.squareup.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:91)
    at io.grpc.transport.okhttp.OkHttpClientTransport.start(OkHttpClientTransport.java:293)
    ... 17 more
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb7971fb0: Failure in SSL library, usually a protocol error
error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available (external/openssl/ssl/s23_clnt.c:486 0xabd7dd5c:0x00000000)
    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
    ... 19 more
]>
    at io.grpc.android.integrationtest.TesterActivityTest.testGrpc(TesterActivityTest.java:56)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
    at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
    at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
    at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

Test results for InstrumentationTestRunner=.F
Time: 3.513

FAILURES!!!
Tests run: 1,  Failures: 1,  Errors: 0
```

**Comment by madongfly** [comment]
API level 18 has the same problem.

BTW, the server side didn't output any info.

**Comment by madongfly** [comment]
The reason is these targets don't have gms.

Using Google-api-19 works, but Google-api-18's gms reported SERVICE_VERSION_UPDATE_REQUIRED, there is a way to pop up  a dialog to let users upgrade gms, but according to Jie from gms team, there is no way to upgrade silently. :(

Still fighting with.

**Comment by madongfly** [comment]
api-20 (Wear) has the same problem.
